image: "redoxos/redoxer"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git

build:linux:
  stage: build
  script:
    - cargo build
    - make tests
  cache:
    paths:
      - cargo/
      - target/

build:redox:
  stage: build
  script:
    - redoxer build --verbose
  cache:
    paths:
      - cargo/
      - target/

test:linux:
    stage: test
    dependencies:
        - build:linux
    script:
      - cargo test