[package]
name = "dces"
version = "0.1.3"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "DCES entity component system"
documentation = "https://docs.rs/dces"
license = "MIT"
repository = "https://gitlab.com/orbtk/dces-rust"
keywords = ["ecs", "ui", "gamedev"]
readme = "README.md"
edition = "2018"