[package]
name = "dces"
version = "0.1.2"
authors = ["OrbTk Focus Time Group"]
description = "DCES entity component system"
documentation = "https://docs.rs/dces"
license = "MIT"
repository = "https://gitlab.com/orbtk/dces-rust"
keywords = ["ecs", "ui", "gamedev"]
readme = "README.md"
